version: '3'
services:
    php:
        container_name: app-cp-exercise
        build: ./docker/php
        restart: always
        expose:
            - "9000"
            - "9001"
        volumes:
            - "./:/app"
    webserver:
        image: nginx:alpine
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./code:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs/:/var/log/nginx/
        links:
            - php