App\Model\Task:
    properties:
        day:
            - DateTime:
                format: d/m/y
        time:
            - DateTime:
                format: H:i
        location:
            - Regex: '/[A-Za-z][A-Za-z0-9]*/'
        covers:
            - Type:
                type: integer

App\Model\Vendor:
    properties:
        name:
            - Regex: '/[A-Za-z ]*/'
        postcode:
            - Regex: '/^[A-Za-z]{1}[A-Za-z0-9]*/'

        maxCovers:
            - Type:
                type: integer
            - GreaterThan:
                value: 0

App\Model\MenuItem:
    properties:
        name:
            - Regex: '/[A-Za-z ]*/'
        allergies:
            - Regex: '/[A-Za-z]*/'
        advanceTime:
            - Regex: '/\d*/'
